name: CI

env:
  JDK_V: "17"

on: [push]

jobs:
  tests:
    name: run tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: apt update
        run: sudo apt update
      - name: remove prev sdk
        run: |
          sudo apt autoremove openjdk*
          sudo apt autoremove java*
      - name: install jdk17
        run: |
          sudo apt install openjdk-${{ env.JDK_V }}-jdk
          echo "-------------------------JDK---------------------------"
          java -version
          echo "-----------------------VERSION-------------------------"
      - name: install maven
        run: sudo apt install maven
      - name: terminal reload
        run: sudo reboot
      - name: run maven test
        run: mvn test
