name: CI

env:
  JDK_V: "17"

on: [push]

jobs:
  tests:
    name: run tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: prepare server
        run: |
          apt update
          apt install openjdk-${{ env.JDK_V }}-jdk
          java -version
          apt install maven
      - name: run maven test
        run: mvn test
